In [2]:
import numpy as np

In [3]:
a = np.zeros(3)

#float zeroes
a


array([0., 0., 0.])

In [18]:

z = np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
z.shape

(10,)

In [31]:
z.shape = (10, 1)
z


array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [32]:
z.shape = (5, 2)
z

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [33]:

z.shape = (2, 5)
z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [34]:

z.shape = (1, 10)
z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [35]:
z = np.ones(10)
z

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [36]:
z = np.empty(3)
z

array([0., 0., 0.])

In [38]:
z = np.linspace(2,10,5) # from 2 to 10 with 5 elements
z

array([ 2.,  4.,  6.,  8., 10.])

In [39]:
z = np.array([10,20])  # ndarray from Python list
z

array([10, 20])

In [42]:
a_list = [1,2,3,4,5,6,7,]
z = np.array([a_list])
z

array([[1, 2, 3, 4, 5, 6, 7]])

In [45]:
b_list = [[9,8,7,6,5,4,3],[1,2,3,4,5,6,7]]
z = np.array([b_list])

In [46]:
b_list

[[9, 8, 7, 6, 5, 4, 3], [1, 2, 3, 4, 5, 6, 7]]

In [48]:
z 

array([[[9, 8, 7, 6, 5, 4, 3],
        [1, 2, 3, 4, 5, 6, 7]]])

In [49]:
type(z)

numpy.ndarray

In [50]:
type(b_list)

list

In [58]:
?b_list

Type:        list
String form: [[9, 8, 7, 6, 5, 4, 3], [1, 2, 3, 4, 5, 6, 7]]
Length:      2
Docstring:  
Built-in mutable sequence.

If no argument is given, the constructor creates a new empty list.
The argument must be an iterable if specified.

In [57]:
z.shape

?z.shape

Type:        tuple
String form: (1, 2, 7)
Length:      3
Docstring:  
Built-in immutable sequence.

If no argument is given, the constructor returns an empty tuple.
If iterable is specified the tuple is initialized from iterable's items.

If the argument is a tuple, the return value is the same object.

In [ ]:
np.random.seed(0)
z1 = np.random.randint(